version: '2'
services:
   web:
     image: palampallidivyasree/front:v.0
     container_name: frontsise
     restart: always
     expose:
       - 86
     ports:
       - 86:80
       
   flask:
       #build: back-docker
            #context: ../.
            #dockerfile: 
       image: palampallidivyasree/back:v.1
       container_name: backdivya
       #workdir: /app
       restart: always
       expose:
         - 5000
       ports:
         - 5000:5000